https://localhost:8080/client/
Authorization: Basic admin secret

###
POST https://localhost:8080/client/new HTTP/1.1
content-type: application/json

{
    "name": "Martine",
    "email": "Martine.vv@hotmail.com",
    "password": "Azerty123"
}
###

POST http://localhost:8080/client/new HTTP/1.1
content-type: application/json

{
    "name": "Peter",
    "email": "Pwkm@telenet.be",
    "password": "Azerty123"
}

###
http://localhost:8080/client/01efaaaa-584e-6a78-b009-f2790ce2618c

###

DELETE http://localhost:8080/client/01ef9f65-59c2-65ac-a6de-b62758b2695c

###

POST http://localhost:8080/product/new HTTP/1.1
content-type: application/json

{
    "name": "Verplichte verzekering - Basic",
    "description": "Standaard verplichte verzekering voor standaard persoon",
    "annualcontribution": 125
}